sudo: required
servics:
  - docker

before_install:
  - docker build -t tlinford/react-test -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tlinford/react-test npm test

after_success:
  - docker build -t "$DOCKER_ID"/multi-client ./client
  - docker build -t "$DOCKER_ID"/multi-nginx ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server
  - docker build -t "$DOCKER_ID"/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push "$DOCKER_ID"/multi-client
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-worker
